// CCNA Helper – corrected for numbers and strings
(function() {
    const qa = [
        { q: "Un administrateur a défini un compte d'utilisateur local avec un mot de passe secret sur le routeur R1 pour être utiliser avec SSH. Quelles sont les trois étapes supplémentaires nécessaires pour configurer R1 pour accepter uniquement les connexions SSH chiffrées ?",
          a: "Activez les sessions SSH entrantes à l'aide des commandes de ligne VTY. Configurer le nom de domaine IP. Générer les clés SSH." },
        { q: "Que sont les protocoles propriétaires ?",
          a: "Des protocoles développés par des entreprises qui contrôlent leur définition et leur fonctionnement." },
        { q: "Reliez chaque description au terme : Dimensionnement des messages / Encapsulation des messages / Codage des messages",
          a: "Dimensionnement → décomposer un message long en parties distinctes. Encapsulation → placer un format de message à l'intérieur d'un autre. Codage → convertir des informations dans un format acceptable." },
        { q: "Quel est le plus petit masque réseau pour 4 périphériques ?",
          a: "255.255.255.248 (/29)" },
        { q: "À quoi sert le glissement de fenêtre TCP ?",
          a: "À demander à une source de réduire la vitesse à laquelle elle transmet les données." },
        { q: "Quelles sont les 3 affirmations qui décrivent la fonction TCP ou UDP ?",
          a: "Le champ Port source identifie l'application/service actif. Des segments UDP sont encapsulés dans des paquets IP. Le numéro de port de destination UDP identifie l'application/service du serveur." },
        { q: "Port 69 = quelle application ?",
          a: "TFTP" },
        { q: "Quelle caractéristique décrit un cheval de Troie ?",
          a: "Logiciel ou code malveillant s'exécutant sur un périphérique final." },
        { q: "Quels sont les 2 problèmes causés par un grand nombre de requêtes ARP ?",
          a: "Tous les messages de requête ARP doivent être traités par tous les nœuds du réseau local. La requête ARP est envoyée en tant que diffusion et inondera l'ensemble du sous-réseau." },
        { q: "Commande Windows pour afficher la configuration IP ?",
          a: "ipconfig" },
        { q: "Que fait \"service password-encryption\" ?",
          a: "Elle chiffre les mots de passe stockés dans les fichiers de configuration." },
        { q: "Mécanisme pour empêcher un paquet IPv4 de voyager sans fin ?",
          a: "Il décrémente la valeur du champ TTL de 1. Si résultat = 0, il rejette le paquet et envoie 'Time Exceeded'." },
        { q: "Service fourni par HTTPS ?",
          a: "Utilise le cryptage pour sécuriser l'échange de texte, images, sons et vidéos sur le Web." },
        { q: "2 caractéristiques d'une table de routage IPv4 ?",
          a: "Stocke des informations sur les chemins dérivés des interfaces de routeur actives. Si une route statique par défaut est configurée, code source S." },
        { q: "Valeur diminuée par chaque routeur dans en-tête IPv4 ?",
          a: "Time To Live (TTL)" },
        { q: "Passerelle par défaut de l'hôte H1 ?",
          a: "R1: G0/0" },
        { q: "Effet de \"ip default-gateway 172.16.100.1\" sur un commutateur ?",
          a: "Le commutateur peut être géré à distance depuis un hôte sur un autre réseau." },
        { q: "Moyen le plus rapide de vérifier une bannière ?",
          a: "Quittez le mode d'exécution privilégié et appuyez sur Enter." },
        { q: "Méthode de gestion des conflits sur réseau sans fil ?",
          a: "CSMA/CA" },
        { q: "3 caractéristiques du CSMA/CD ?",
          a: "Suite à une collision, les hôtes tentent après un délai aléatoire. Un périphérique écoute le support et attend qu'il soit libre. Un signal d'encombrement indique que la collision est résolue." },
        { q: "Champ qui vérifie si un signal a été modifié ?",
          a: "Champ Séquence de contrôle de trame (FCS)" },
        { q: "Technologie sans fil pour applications domotiques (faible consommation/débit) ?",
          a: "ZigBee" },
        { q: "Problème avec le raccordement RJ-45 ?",
          a: "La longueur détorsadée de chaque fil est trop longue." },
        { q: "3 points à considérer pour conception réseau sans fil ?",
          a: "Options de mobilité, Zone de couverture, Sécurité (ou Perturbation)." },
        { q: "Masque pour max sous-réseaux avec au moins 100 hôtes ?",
          a: "255.255.255.128 (/25)" },
        { q: "Masque optimal pour 22+20+2+2 adresses sur 192.168.10.0/24 ?",
          a: "255.255.255.224 (/27)" },
        { q: "Associer réseaux aux adresses :",
          a: "A → 192.168.0.128/25 (128 hôtes), B → 192.168.0.0/26 (64 hôtes), C → 192.168.0.96/27 (32 hôtes), D → 192.168.0.80/30 (4 hôtes)." },
        { q: "2 fonctions de la sous-couche MAC (Cas 1) ?",
          a: "Ajoute des infos de contrôle Ethernet ; gère la communication entre logiciel et matériel." },
        { q: "2 fonctions de la sous-couche MAC (Cas 2) ?",
          a: "Implémente CSMA/CD ; gère la communication entre logiciel et matériel." },
        { q: "Type d'infos à vérifier pour comportement normal du réseau ?",
          a: "Les performances de référence du réseau (baseline)." },
        { q: "3 commandes Windows pour vérifier IP/DNS/connectivité ?",
          a: "ipconfig, ping, nslookup" },
        { q: "Serveur avec enregistrements A, NS, AAAA, MX ?",
          a: "DNS" },
        { q: "Ping IP réussi mais pas URL, quelle commande ?",
          a: "nslookup" },
        { q: "Store-and-forward vs cut-through ?",
          a: "Store-and-forward stocke toute la trame, vérifie CRC ; cut-through a moins de latence." },
        { q: "2 propositions exactes sur IP/MAC sans NAT ?",
          a: "Adresses IP de destination restent les mêmes tout au long du chemin. Adresses MAC changent chaque fois qu'une trame passe d'un réseau à un autre." },
        { q: "Avantage du cloud computing ?",
          a: "L'entreprise améliore ses capacités réseau sans investissement supplémentaire." },
        { q: "2 fonctions d'ARP ?",
          a: "Si un hôte a l'IP mais pas la MAC, il génère une diffusion ARP. Si le périphérique reçoit une requête ARP avec son IP, il renvoie une réponse ARP." },
        { q: "Couches OSI équivalentes à la couche Application TCP/IP ?",
          a: "Application, Présentation, Session." },
        { q: "Que fait R1 de l'en-tête Ethernet de PC1 ?",
          a: "Supprime l'en-tête Ethernet et configure un nouvel en-tête de couche 2." },
        { q: "Service fourni par Internet Messenger ?",
          a: "Application qui permet les discussions en ligne en temps réel." },
        { q: "2 commandes Windows pour afficher la table de routage ?",
          a: "netstat -r, route print" },
        { q: "Associer adresses IP : Bouclage, Expérimentale, Publique, Link-local",
          a: "Bouclage → 127.0.0.1, Expérimentale → 240.2.6.255, Publique → 198.133.219.2, Link-local → 169.254.1.5." },
        { q: "Fonction de la couche transport ?",
          a: "S'assure que la page Web appropriée est envoyée vers la fenêtre de navigateur appropriée." },
        { q: "Qu'est-ce que l'atténuation ?",
          a: "Perte de puissance du signal à mesure que la distance augmente." },
        { q: "Passerelle par défaut incorrecte ?",
          a: "L'hôte ne peut pas communiquer avec les hôtes sur d'autres réseaux." },
        { q: "Malware qui ralentit le réseau (programme scanneur) ?",
          a: "Virus (ou ver)." },
        { q: "Conséquence de \"ipv6 unicast-routing\" ?",
          a: "Les interfaces activées IPv6 envoient des messages d'annonces de routeur ICMPv6." },
        { q: "PDU de l'hôte B au routeur (couche 2 et 3) ?",
          a: "L2 dest = 00-00-0c-94-36-cd, L2 src = 00-00-0c-94-36-bb, L3 dest = 172.16.20.99, L3 src = 172.16.10.200." },
        { q: "3 caractéristiques du réseau (scénario vidéoconférence + basculement) ?",
          a: "Qualité de service, tolérance aux pannes, sécurité." },
        { q: "Composant AAA pour droits lecture/écriture ?",
          a: "Autorisation." },
        { q: "Problème avec \"configure terminal\" en mode utilisateur ?",
          a: "L'administrateur doit d'abord passer en mode d'exécution privilégié (enable)." },
        { q: "3 conditions de transmission définies par les protocoles ?",
          a: "Le codage des messages, la taille du message, les options de remise du message." },
        { q: "2 causes de dégradation du signal UTP ?",
          a: "Résiliation abusive, câble ou connecteurs de mauvaise qualité." },
        { q: "2 protocoles de la couche supérieure TCP/IP ?",
          a: "POP, DNS." },
        { q: "2 caractéristiques du protocole IP ?",
          a: "Fonctionne indépendamment des supports réseau ; ne nécessite pas de connexion dédiée de bout en bout." },
        { q: "Sous-réseau contenant 192.168.1.96 comme hôte utilisable ?",
          a: "192.168.1.64/26" },
        { q: "2 méthodes pour évaluer le trafic avec analyseur ?",
          a: "Capturer en période de pointe ; capturer sur plusieurs segments." },
        { q: "2 affirmations sur résultat de ping/tracert ?",
          a: "Il existe 4 sauts ; connectivité établie." },
        { q: "EUI-64 avec MAC 1C-6F-65-C2-BD-F8 ?",
          a: "1E6F:65FF:FEC2:BDF8" },
        { q: "Destination de FF02::2 ?",
          a: "Tous les routeurs IPv6 configurés sur la liaison locale." },
        { q: "Que fait le client SLAAC avant d'utiliser une adresse IPv6 ?",
          a: "Il envoie un message de sollicitation de voisin ICMPv6 (DAD)." },
        { q: "Type d'attaque : employé utilise des outils wifi gratuits ?",
          a: "Reconnaissance." },
        { q: "\"show startup-config\" affiche quoi ?",
          a: "Le contenu du fichier de configuration enregistré dans la NVRAM." },
        { q: "Masque sous-réseau pour 3 sous-réseaux (10, 8, 2 adresses) ?",
          a: "255.255.255.240 (/28)" },
        { q: "3 normes pour câblage ?",
          a: "Brochage, longueur des câbles, types de connecteurs." },
        { q: "Connecteur pour paires torsadées Ethernet ?",
          a: "RJ-45" },
        { q: "Technique UTP contre la diaphonie ?",
          a: "Enrouler les brins en hélice pour former des paires torsadées." },
        { q: "2 facteurs interférant avec câblage cuivre près d'éclairages ?",
          a: "EMI, RFI." },
        { q: "Service fourni par DNS ?",
          a: "Traduit des noms de domaines en adresses IP." },
        { q: "Hôte A cherche MAC passerelle : qui reçoit la requête ARP ?",
          a: "Uniquement les hôtes B, C et le routeur R1." },
        { q: "2 fonctions de la couche réseau ?",
          a: "Diriger les paquets vers les hôtes de destination ; fournir un identificateur réseau unique." },
        { q: "2 propositions correctes IPv4 vs IPv6 ?",
          a: "TTL remplacé par Hop Limit ; le nom Source Address est conservé." },
        { q: "Caractéristique d'un virus ?",
          a: "Logiciel qui identifie les menaces qui se propagent rapidement (ou logiciel malveillant)." },
        { q: "Priorités QoS (audio, transactions, web) ?",
          a: "Conférence audio > transactions financières > page Web." },
        { q: "Plus petit masque pour 200 périphériques ?",
          a: "255.255.255.0 (/24)" },
        { q: "Fonction de la couche liaison de données ?",
          a: "Prévoit l'échange de trames sur un média local commun." },
        { q: "Comment obtenir adresse MAC pour réseau distant ?",
          a: "Il envoie une requête ARP pour l'adresse MAC de la passerelle par défaut." },
        { q: "Méthode qui supprime les trames qui échouent au FCS ?",
          a: "Commutation par stockage et retransmission (store-and-forward)." },
        { q: "Avantage IMAP vs POP ?",
          a: "Les messages sont stockés sur les serveurs jusqu'à suppression manuelle." },
        { q: "Couches TCP/IP pour transfert fichier ?",
          a: "Application, transport, Internet, accès réseau." },
        { q: "Outil avec privilèges admin pour localiser problème réseau lent ?",
          a: "tracert" },
        { q: "Plage d'adresses link-local IPv6 ?",
          a: "FE80::/10" },
        { q: "Port 22 = quelle application ?",
          a: "SSH" },
        { q: "2 fonctions de la sous-couche LLC ?",
          a: "Place les infos indiquant le protocole de couche réseau ; permet à IPv4 et IPv6 d'utiliser le même support." },
        { q: "2 caractéristiques communes TCP et UDP ?",
          a: "La numérotation des ports ; l'utilisation de sommes de contrôle." },
        { q: "Plus petit masque pour 61 périphériques ?",
          a: "255.255.255.192 (/26)" },
        { q: "2 configurations pour accéder à http://www.cisco.com ?",
          a: "Serveur DNS, Passerelle par défaut." },
        { q: "Service fourni par DHCP ?",
          a: "Affecte dynamiquement des adresses IP aux périphériques." },
        { q: "Sous-réseaux possibles avec 2001:db8:0:ca00::/56 ?",
          a: "256 (car 8 bits pour sous-réseau = 2^8)." },
        { q: "Comment l'ordinateur suit les flux entre applications ?",
          a: "Par le numéro de port source utilisé par chaque application." },
        { q: "Pourquoi un switch L2 a besoin d'une IP ?",
          a: "Pour permettre au commutateur d'être géré à distance." },
        { q: "Menace : tableur désactive le pare-feu ?",
          a: "Cheval de Troie." },
        { q: "Caractéristique de la couche liaison de données ?",
          a: "Elle empêche la couche supérieure de connaître le support physique." },
        { q: "NIC au niveau couche liaison de données ?",
          a: "Adresse MAC." },
        { q: "Ping passerelle échoue mais ping externe réussi ?",
          a: "Des règles de sécurité sont appliquées à la passerelle par défaut." },
        { q: "2 problèmes de la fibre optique ?",
          a: "Plus coûteuse que le cuivre ; nécessite expertise différente pour terminaison/épissage." },
        { q: "\"transport input ssh\" sur les lignes vty ?",
          a: "La communication entre le commutateur et les utilisateurs distants est cryptée." },
        { q: "Si seuil d'erreur atteint sur port, méthode de repli ?",
          a: "store-and-forward" },
        { q: "2 types de trafic utilisant RTP ?",
          a: "Voix, Vidéo." },
        { q: "2 messages ICMPv6 absents dans ICMPv4 ?",
          a: "Sollicitation de voisin, Annonce de routeur (ou Annonce de voisin)." },
        { q: "Service fourni par SMTP ?",
          a: "Permet aux clients d'envoyer des courriels à un serveur de messagerie." },
        { q: "2 messages ICMPv6 pour résolution adresse MAC ?",
          a: "Sollicitation de voisin, Annonce de voisin." },
        { q: "Mode d'accès le plus approprié pour confidentialité ?",
          a: "SSH" },
        { q: "Port 110 = quelle application ?",
          a: "POP3" },
        { q: "Si masque 255.255.255.192 sur 192.168.99.0, combien d'adresses inutilisées ?",
          a: "72 (selon illustration)." },
        { q: "2 fonctions de la sous-couche LLC (bis) ?",
          a: "Place les infos sur le protocole de couche réseau ; ajoute des infos de contrôle Ethernet." },
        { q: "2 méthodes les plus efficaces contre les malwares ?",
          a: "Installer/mettre à jour un antivirus ; mettre à jour OS et logiciels." },
        { q: "Adresse MAC de destination dans la trame (hôte A vers hôte B via routeur) ?",
          a: "BB:BB:BB:BB:BB:BB (l'interface du routeur)." },
        { q: "Port 21 = quelle application ?",
          a: "FTP" },
        { q: "Service fourni par POP3 ?",
          a: "Récupère le courrier en téléchargeant vers l'application locale." },
        { q: "Masque pour 40 terminaux sans gaspillage ?",
          a: "255.255.255.192 (/26)" },
        { q: "Port 80 = quelle application ?",
          a: "HTTP" },
        { q: "Plus petit masque pour 10 périphériques ?",
          a: "255.255.255.240 (/28)" },
        { q: "Protocole responsable de la table (arp -a) ?",
          a: "ARP" },
        { q: "PC1 envoie ARP à PC2, que se passe-t-il ?",
          a: "PC2 envoie une réponse ARP contenant son adresse MAC." },
        { q: "Avantage d'un protocole à norme ouverte ?",
          a: "Il favorise la compétitivité et permet de choisir." },
        { q: "2 responsabilités de la sous-couche MAC Ethernet ?",
          a: "Accès aux supports, détection des erreurs (ou délimitation des trames)." },
        { q: "Modèle de réseau : imprimante partagée sans serveur dédié ?",
          a: "Peer-to-peer (P2P)." },
        { q: "Que fait le routeur après avoir trouvé la correspondance ?",
          a: "Commuter le paquet vers l'interface directement connectée." },
        { q: "3 parties d'une adresse IPv6 monodiffusion globale ?",
          a: "ID de sous-réseau, préfixe de routage global, ID d'interface." },
        { q: "Couche TCP/IP qui transfère les messages via l'interréseau ?",
          a: "Internet (couche réseau)." },
        { q: "Port 67 = quelle application ?",
          a: "DHCP" },
        { q: "Port 53 = quelle application ?",
          a: "DNS" },
        { q: "Port 143 = quelle application ?",
          a: "IMAP" },
        { q: "Plus petit masque pour 25 périphériques ?",
          a: "255.255.255.224 (/27)" },
        { q: "Caractéristique d'une attaque DoS ?",
          a: "Attaque qui ralentit ou bloque un appareil ou un service réseau." },
        { q: "Caractéristique du vol d'identité ?",
          a: "Utilisation d'identifiants volés pour accéder à des données privées." },
        { q: "IPv6 2001:DA48:FC5:A4:3D1B::1/64 → ID de sous-réseau ?",
          a: "2001:DA48:FC5:A4::/64" },
        { q: "2 infos affichées par \"show ip interface brief\" ?",
          a: "Adresses IP, statuts de la couche 1." },
        { q: "Plus petit masque pour 90 périphériques ?",
          a: "255.255.255.128 (/25)" },
        { q: "Service fourni par HTTP ?",
          a: "Ensemble de règles pour échanger texte, graphiques, sons, vidéos sur le Web." },
        { q: "Service fourni par FTP ?",
          a: "Permet les transferts de données entre un client et un serveur de fichiers." },
        { q: "Service fourni par BOOTP ?",
          a: "Application héritée pour découvrir sa propre IP et trouver un serveur BOOTP." },
        { q: "Quand un routeur arrête-t-il de transférer un paquet tracert ?",
          a: "Lorsque la valeur du champ TTL atteint zéro." },
        { q: "Caractéristique d'un ISP ?",
          a: "Logiciel qui identifie les menaces à propagation rapide (IPS)." },
        { q: "Caractéristique d'un VPN ?",
          a: "Protocole de tunnel pour accès sécurisé au réseau d'une organisation." },
        { q: "Caractéristique d'un logiciel espion (spyware) ?",
          a: "Logiciel installé sur l'appareil et collectant des informations sur l'utilisateur." },
        { q: "Caractéristique d'un logiciel publicitaire (adware) ?",
          a: "Logiciel installé sur l'appareil et collectant des informations sur l'utilisateur." },
        { q: "Caractéristique d'un antivirus ?",
          a: "Applications qui protègent les terminaux contre les malwares." },
        { q: "Caractéristique d'un antispyware ?",
          a: "Applications qui protègent les terminaux contre les malwares." },
        { q: "2 solutions sécurité surtout en entreprise ?",
          a: "VPN, systèmes de prévention des intrusions (IPS)." },
        { q: "2 déclarations sur NAT ?",
          a: "NAT introduit des problèmes pour certaines applications ; NAT ralentit l'épuisement des adresses IPv4." },
        { q: "Zigbee pour IoT (faible consommation/débit) ?",
          a: "Vrai." }
    ];

    function byNumber(num) {
        if (num >= 1 && num <= qa.length) return qa[num-1];
        return null;
    }

    function byKeyword(keyword) {
        const kw = keyword.toLowerCase();
        return qa.filter((item, idx) => item.q.toLowerCase().includes(kw))
                 .map((item, idx) => ({ num: idx+1, q: item.q, a: item.a }));
    }

    window.ccna = function(query) {
        // Convert query to string and trim (handles numbers directly)
        let q = String(query).trim();
        if (q === "") {
            console.log("Usage: ccna('numéro')  ou  ccna('mot-clé')");
            return;
        }
        const num = parseInt(q, 10);
        if (!isNaN(num)) {
            const item = byNumber(num);
            if (item) {
                console.log(`\n📌 Question ${num}:\n${item.q}\n✅ Réponse:\n${item.a}\n`);
            } else {
                console.log(`❌ Question ${num} non trouvée (max ${qa.length})`);
            }
        } else {
            const results = byKeyword(q);
            if (results.length === 0) {
                console.log(`❌ Aucune question contenant "${q}"`);
            } else if (results.length === 1) {
                console.log(`\n📌 Question ${results[0].num}:\n${results[0].q}\n✅ Réponse:\n${results[0].a}\n`);
            } else {
                console.log(`🔎 ${results.length} questions trouvées pour "${q}" :`);
                results.slice(0, 8).forEach(r => {
                    console.log(`  ${r.num}. ${r.q.substring(0, 80)}...`);
                });
                if (results.length > 8) console.log(`  ... et ${results.length-8} autres.`);
                console.log("Utilisez ccna('numéro') pour voir la réponse complète.");
            }
        }
    };

    console.log("✅ CCNA Helper chargé. Tapez ccna('mot-clé') ou ccna(42) dans la console.");
})();
